using BusinessLayer.CLI.Utils.Enums;
using BusinessLayer.DTOs;
using BusinessLayer.Services.Interfaces;
using NBitcoin;
using ResultPattern;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BusinessLayer.Services
{
    public class DecodeService : IDecodeService
    {
        // First, an initial entropy of ENT bits is generated.
        // A checksum is generated by taking the first ENT / 32 bits of its SHA256 hash.
        // This checksum is appended to the end of the initial entropy.
        // Next, these concatenated bits are split into groups of 11 bits.
        // Each encoding a number from 0-2047, serving as an index into a wordlist. 
        // Finally, we convert these numbers into words and use the joined words as a mnemonic sentence. 
        // https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki#wordlist
        private static byte[] GetEntropy(Mnemonic mnemonic)
        {
            string[] words = mnemonic.Words;
            string[] wordlist = mnemonic.WordList.GetWords().ToArray();

            // Convert each word to 11-bit index and build full bitstring
            var bits = new StringBuilder();
            foreach (var word in words)
            {
                int index = Array.IndexOf(wordlist, word);
                bits.Append(Convert.ToString(index, 2).PadLeft(11, '0'));
            }

            // Separate entropy bits from checksum bits
            string bitString = bits.ToString();
            int totalBits = bitString.Length;
            int checksumBits = totalBits / 33;
            int entropyBits = totalBits - checksumBits;
            string entropyBitsString = bitString.Substring(0, entropyBits);

            // Convert binary string to byte array
            return Enumerable.Range(0, entropyBitsString.Length / 8)
                .Select(i => Convert.ToByte(entropyBitsString.Substring(i * 8, 8), 2))
                .ToArray();
        }

        public Result<DecodeDTO> Decode(string phrase, ValueFormat format)
        {

            Mnemonic mnemonic;

            // 1. Handle invalid wordlist, unknown words, wrong length, etc.
            try
            {
                mnemonic = new Mnemonic(phrase, Wordlist.English);
            }
            catch (Exception ex)
            {
                return Result.Fail<DecodeDTO>($"Invalid mnemonic: {ex.Message}");
            }

            // 2. Handle invalid checksum (wrong last word)
            if (!mnemonic.IsValidChecksum)
            {
                return Result.Fail<DecodeDTO>("Invalid mnemonic checksum.");
            }


            byte[] entropy = GetEntropy(mnemonic);

            byte[] seed = mnemonic.DeriveSeed();

            return Result.Ok(new DecodeDTO
            {
                Mnemonic = mnemonic,
                Entropy = entropy,
                Seed = seed,
                Format = format
            });
        }
    }
}
